# Generated by Django 5.2.4 on 2025-08-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('tenth_school_name', models.CharField(max_length=200)),
                ('twelfth_school_name', models.CharField(max_length=200)),
                ('tenth_hindi', models.IntegerField()),
                ('tenth_english', models.IntegerField()),
                ('tenth_social_science', models.IntegerField()),
                ('tenth_science', models.IntegerField()),
                ('tenth_maths', models.IntegerField()),
                ('twelfth_hindi', models.IntegerField()),
                ('twelfth_english', models.IntegerField()),
                ('twelfth_physics', models.IntegerField()),
                ('twelfth_chemistry', models.IntegerField()),
                ('twelfth_maths', models.IntegerField()),
            ],
        ),
    ]
