# Generated by Django 5.2.4 on 2025-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_english',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_hindi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_maths',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_school_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_science',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_social_science',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_chemistry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_english',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_hindi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_maths',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_physics',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_school_name',
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='english_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='english_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='hindi_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='hindi_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='physics_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='pref1',
            field=models.CharField(default='Not Selected', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pref2',
            field=models.CharField(default='Not Selected', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='school_10',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='school_12',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='science_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='social_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
