# Generated by Django 5.2.4 on 2025-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student', 
            name='chemistry_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='hindi_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='hindi_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='pref1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='pref2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_10',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_12',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_12',
            field=models.IntegerField(),
        ),
    ]
