# Generated by Django 5.2.4 on 2025-08-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_student_chemistry_12_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Information',
        ),
    ]
