# Generated by Django 5.2.4 on 2025-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_student_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('highschool_name', models.CharField(max_length=100)),
                ('intermediate_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('hs_hindi', models.PositiveIntegerField()),
                ('hs_english', models.PositiveIntegerField()),
                ('hs_social_science', models.PositiveIntegerField()),
                ('hs_science', models.PositiveIntegerField()),
                ('hs_math', models.PositiveIntegerField()),
                ('inter_hindi', models.PositiveIntegerField()),
                ('inter_english', models.PositiveIntegerField()),
                ('inter_physics', models.PositiveIntegerField()),
                ('inter_chemistry', models.PositiveIntegerField()),
                ('inter_math', models.PositiveIntegerField()),
                ('pref1', models.CharField(max_length=50)),
                ('pref2', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
