# Generated by Django 5.2.4 on 2025-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_studentcounselling_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounselling',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='admission_letters/'),
        ),
        migrations.AddField(
            model_name='studentcounselling',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcounselling',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
